// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import EnergyController from "./energy_controller"
application.register("energy", EnergyController)

import EquipModalController from "./equip_modal_controller"
application.register("equip-modal", EquipModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
