// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BattleController from "./battle_controller"
application.register("battle", BattleController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import EnergyController from "./energy_controller"
application.register("energy", EnergyController)

import PetRevealController from "./pet_reveal_controller"
application.register("pet-reveal", PetRevealController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LimitController from "./limit_controller"
application.register("limit", LimitController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SleepController from "./sleep_controller"
application.register("sleep", SleepController)

import PetListController from "./pet_list_controller"
application.register("pet-list", PetListController)

import GlowPreviewController from "./glow_preview_controller"
application.register("glow-preview", GlowPreviewController)

import ExplorationListController from "./exploration_list_controller"
application.register("exploration-list", ExplorationListController)

import LoadingButtonController from "./loading_button_controller"
application.register("loading-button", LoadingButtonController)

import ActionPanelController from "./action_panel_controller"
application.register("action-panel", ActionPanelController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import PetCoinsController from "./pet_coins_controller"
application.register("pet-coins", PetCoinsController)


import PartySelectorController from "./party_selector_controller"
application.register("party-selector", PartySelectorController)

import InventoryController from "./inventory_controller"
application.register("inventory", InventoryController)

import OpenContainerController from "./open_container_controller"
application.register("open-container", OpenContainerController)

import ContainerRevealController from "./container_reveal_controller"
application.register("container-reveal", ContainerRevealController)

import OverflowMenuController from "./overflow_menu_controller"
application.register("overflow-menu", OverflowMenuController)

import PetHubController from "./pet_hub_controller"
application.register("pet-hub", PetHubController)

import SlotCountdownController from "./slot_countdown_controller"
application.register("slot-countdown", SlotCountdownController)

import PetDisplayController from "./pet_display_controller"
application.register("pet-display", PetDisplayController)

import BadgeTrackerController from "./badge_tracker_controller"
application.register("badge-tracker", BadgeTrackerController)

import BadgeBuilderController from "./badge_builder_controller"
application.register("badge-builder", BadgeBuilderController)

import TabbarController from "./tabbar_controller"
application.register("tabbar", TabbarController)

import CareAlertsController from "./care_alerts_controller"
application.register("care-alerts", CareAlertsController)

import EncounterBuilderController from "./encounter_builder_controller"
application.register("encounter-builder", EncounterBuilderController)

import PetDetailController from "./pet_detail_controller"
application.register("pet-detail", PetDetailController)
