# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: forgegrind_development

test:
  <<: *default
  database: forgegrind_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: forgegrind_production
  cache:
    <<: *primary_production
    database: forgegrind_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: forgegrind_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: forgegrind_production_cable
    migrations_paths: db/cable_migrate