# Name of your application. Used to uniquely configure containers.
service: forgegrind

# Name of the container image.
image: rickymm3/forgegrind

# Deploy to these servers.
servers:
  web:
    - 34.82.106.188

# Configure builder setup.
builder:
  arch: amd64

registry:
  username: rickymm3
  password:
    - KAMAL_REGISTRY_PASSWORD


env:
  clear:
    DB_HOST: 192.168.0.2
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: gcp


accessories:
  postgres:
    image: postgres:16
    host: 34.82.106.188
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: rails_user
        POSTGRES_DB: forgegrind_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    files:
      - db/production_setup.sql:/docker-entrypoint-initdb.d/setup.sql