# config/items.yml
#
# Centralised item catalogue used for seeding Items and rendering UI metadata.
# Keys are the canonical `item_type` strings; values expose a display `name`,
# descriptions, and optional personality modifiers that various UIs reference.

starter_item:
  name: "Starter Item"
  description: "A basic supplies kit - humble beginnings for any caretaker."
  rarity: common

wooden_stick:
  name: "Wooden Stick"
  description: "A sturdy stick; simple, reliable, and oddly comforting."
  rarity: common

frisbee:
  name: "Frisbee"
  description: "A playful frisbee to toss around with your pet."
  playfulness_mod: 0.5
  affection_mod: 0.0
  temperament_mod: 0.0
  curiosity_mod: 0.2
  confidence_mod: 0.0
  usable: true
  target_type: pet
  rarity: uncommon

blanket:
  name: "Blanket"
  description: "A cozy blanket that makes your pet feel safe and warm."
  playfulness_mod: 0.0
  affection_mod: 0.5
  temperament_mod: 0.1
  curiosity_mod: 0.0
  confidence_mod: 0.2
  usable: true
  target_type: pet
  rarity: uncommon

soap:
  name: "Soap"
  description: "A gentle cleanser that keeps coats gleaming."
  playfulness_mod: 0.0
  affection_mod: 0.5
  temperament_mod: 0.1
  curiosity_mod: 0.0
  confidence_mod: 0.2
  usable: true
  target_type: pet
  rarity: rare

whistle:
  name: "Whistle"
  description: "A whistle that grabs your pet's attention instantly."
  playfulness_mod: 0.0
  affection_mod: -0.2
  temperament_mod: 0.5
  curiosity_mod: 0.0
  confidence_mod: 0.1
  usable: true
  target_type: pet
  rarity: rare

treat:
  name: "Treat"
  description: "A tasty treat that boosts your pet's mood."
  playfulness_mod: 0.0
  affection_mod: 0.3
  temperament_mod: 0.0
  curiosity_mod: 0.4
  confidence_mod: 0.0
  usable: true
  target_type: pet
  rarity: common

map:
  name: "Map"
  description: "A detailed map to help you and your pet explore new areas."
  playfulness_mod: 0.0
  affection_mod: 0.0
  temperament_mod: 0.0
  curiosity_mod: 0.5
  confidence_mod: 0.2
  usable: true
  target_type: pet
  rarity: uncommon

leveling_stone:
  name: "Leveling Stone"
  description: "A steady stone that safely channels growth for any pet."
  rarity: rare

normal_stone:
  name: "Normal Stone"
  description: "A versatile stone attuned to well-balanced companions."
  rarity: uncommon

fire_stone:
  name: "Fire Stone"
  description: "Warm to the touch - fire-aligned pets resonate with its ember core."
  rarity: rare

water_stone:
  name: "Water Stone"
  description: "Cool and fluid, perfect for aquatic or flowy personalities."
  rarity: rare

electric_stone:
  name: "Electric Stone"
  description: "Crackling with residual charge, it energizes electric pets."
  rarity: rare

grass_stone:
  name: "Grass Stone"
  description: "Verdant moss covers this stone; nurturing for nature-aligned pets."
  rarity: rare

ice_stone:
  name: "Ice Stone"
  description: "Chilled frost clings to its surface, harmonizing with icy temperaments."
  rarity: rare

shadow_stone:
  name: "Shadow Stone"
  description: "Whispers of dusk swirl inside, guiding shadow-bound companions."
  rarity: rare

metal_stone:
  name: "Metal Stone"
  description: "Dense and steady, forged for metallic hides and hardy shells."
  rarity: rare

wind_stone:
  name: "Wind Stone"
  description: "Light as air; its currents thrill agile, wind-loving pets."
  rarity: rare

spirit_stone:
  name: "Spirit Stone"
  description: "Glows softly, responding to ethereal, spirit-touched allies."
  rarity: rare

storm_stone:
  name: "Storm Stone"
  description: "Rumbles faintly inside, ideal for tempestuous partners."
  rarity: rare

celestial_stone:
  name: "Celestial Stone"
  description: "Starlight flickers within - perfect for pets attuned to the cosmos."
  rarity: epic
